### ISSUE TITLE
Support for transactions?

### ISSUE THREAD

**Issue by noozo** [codedge-llc/commandex#6]
Hi, first of all thanks for this library, the command module really makes it straightforward to read a module and know what will happen (which parameters are needed, what actions are taken, etc).

Unsure this is the right place, but was wondering whether support for Ecto transactions is in the pipeline (Sage supports it, for instance, and i see this as a simpler alternative to sagas, tbh).

Also, any strong reason why you didn't adopt the typical `:ok | {:error, _whatever}` return structure for commands?

I think those i probably the only two things why i still prefer Sage over your library, even though yours looks cooler and way simpler :)

Thanks again
Pedro

PS: Feel free to close this hehe ;)

**Comment by hpopp** [comment]
Commandex should allow you to run Ecto transactions already, but it may not be very straightforward. The big difference between Sage and Commandex is that this library doesn't automatically execute callbacks on errors. You're expected to put an error on the command struct without halting, and then match it in a subsequent pipeline. Obviously exceptions will halt all execution, so they need to be caught accordingly.

I'm actually in the minority opinion when it comes to tagged tuples. They're great for primitive values, but I frequently avoid them for maps and structs. Everyone seems to have a slightly different structure when it comes to error tuples with multiple errors, and they don't play particularly nicely with protocols and pipes (`elem(1)` anyone?).

I would love if the community would standardize on certain key names in a struct for validity/errors, just like tagged tuples as a standard, but maybe I'm fighting a losing battle.

**Comment by hpopp** [comment]
Also, feel free to hang out on #commandex on the Elixir slack. I'm usually around.

**Comment by noozo** [comment]
Yeah, that's a good point about the multiple errors. Where i work we have standardized a certain way, but of course every company does the same in a different way. I supposed there's no harm in that, we can always adapt to each library we need to.

Thanks for the replies, and also for taking the time to make this open source.
